# Project information
site_name: Docs
site_description: disunaurio_nft Documentation
site_author: iorbegozo
site_url: !!python/object/apply:os.getenv ["SITE_URL"]

# Content
docs_dir: docs

# Repository
repo_name: !!python/object/apply:os.getenv ["REPO_NAME"]
repo_url: !!python/object/apply:os.getenv ["REPO_URL"]
edit_uri: !!python/object/apply:os.getenv ["EDIT_URI"]

# Copyright
copyright: Copyright &copy; 2022

# Configuration
theme:
  name: material
  custom_dir: docs/theme
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/gitlab
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

# Extras
extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://my-webpage.com
    - icon: fontawesome/brands/linkedin
      link: https://es.linkedin.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCF6Brc4lIZfoEk_tB_UlIAQ

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.0.1/mermaid.min.js

# Plugins
plugins:
  - awesome-pages
  - search
  - mkdocstrings
  - build_plantuml:
      render: 'server'
      server: 'http://www.plantuml.com/plantuml'
      output_format: 'png'
      diagram_root: 'docs'
      input_folder: 'diagrams'
      output_folder: '_build/diagrams'
  - gen-files:
      scripts:
        - docs/generate_library_reference.py 
  - render_swagger

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: "./docs"
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.smartsymbols
  - pymdownx.critic
  - footnotes
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - meta

use_directory_urls: false
